# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH="$HOME/.local/bin:$PATH" && uv sync --extra docs --no-dev
    post_install:
      - export PATH="$HOME/.local/bin:$PATH" && uv pip install .

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements file
# python:
#   install:
#     - requirements: docs/requirements.txt
