version: '3.8'

services:
  desto:
    build: .
    ports:
      - "8088:8088"
    volumes:
      # Mount host directories for scripts and logs
      - ./docker-scripts:/app/scripts
      - ./docker-logs:/app/logs
    environment:
      - DESTO_SCRIPTS_DIR=/app/scripts
      - DESTO_LOGS_DIR=/app/logs
    restart: unless-stopped
    container_name: desto-dashboard
    
  # Example with custom directories
  desto-custom:
    build: .
    ports:
      - "8089:8088"
    volumes:
      - ./my-scripts:/app/scripts
      - ./my-logs:/app/logs
    environment:
      - DESTO_SCRIPTS_DIR=/app/scripts
      - DESTO_LOGS_DIR=/app/logs
    profiles:
      - custom
    container_name: desto-custom
