services:
  # Main desto dashboard service without Redis
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desto-dashboard
    ports:
      - "8809:8809"
    volumes:
      - ./desto_scripts:/app/desto_scripts
      - ./desto_logs:/app/desto_logs
      # Mount timezone information to sync with host
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DESTO_SCRIPTS_DIR=/app/desto_scripts
      - DESTO_LOGS_DIR=/app/desto_logs
      # Timezone configuration - set to match host system
      - TZ=Europe/Berlin
      # Disable Redis
      - REDIS_ENABLED=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8809"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
