name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start services with Docker Compose
      run: |
        docker compose up -d --build
        sleep 15
        docker ps

    - name: Basic connectivity test
      run: |
        curl -f http://localhost:8809 || echo "Container is running but endpoint might not be ready"

    - name: Show dashboard logs (for debugging)
      run: |
        docker logs desto-dashboard

    - name: Set up Python environment for integration tests
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync --extra dev

    - name: Run Docker integration tests
      run: |
        uv run --extra dev pytest tests/test_docker_integration.py -v
        uv run --extra dev pytest tests/test_docker_compose.py -v
        uv run --extra dev pytest tests/test_docker_timezone_fix.py -v

    - name: Run additional integration tests (optional)
      run: |
        uv run --extra dev pytest tests/test_dashboard_integration.py -v
        uv run --extra dev pytest tests/test_chain_logging.py -v
        uv run --extra dev pytest tests/test_job_completion_comprehensive.py -v
        uv run --extra dev pytest tests/test_scheduled_jobs_integration.py -v

    - name: Tear down services
      if: always()
      run: |
        docker compose down -v --remove-orphans